### ISSUE TITLE
Can't install web.py?

### ISSUE THREAD

**Issue by agrawalsmart7** [dineshshetty/Android-InsecureBankv2#15] opened 2019-01-03 08:27 UTC
Hi, please tell me Why I can't install web.py by using `pip install -r requirement.txt`?

**Comment by dineshshetty** [comment] 2019-03-06 06:51
I uninstalled web.py specifically and installed it again using pip install -r requirements.txt and it worked fine.
![image](https://user-images.githubusercontent.com/2169995/53861472-561b6f80-400a-11e9-9f54-2aaf5fafaeb1.png)

**Comment by gfhuertac** [comment] 2019-08-09 11:23
The issue is when using python3.
To overcome this issue you need to install an experimental version:
pip install web.py==0.40-dev1

**Comment by javijjavi** [comment] 2020-05-16 20:07
Hi!
I'm trying to install it using pip install -r requirements.txt, but I'm getting some errors.

![Captura](https://user-images.githubusercontent.com/20777366/82129199-4af0d180-97c1-11ea-83ef-1e7eb1d49bc0.PNG)

I'm not sure why it's not working, I'm using the machine santoku.
I think it's something about Python 2 and 3 but I'm not sure...
I try other commands to force the install but same error
Thank you very much, guys!!

**Comment by gfhuertac** [comment] 2020-05-18 12:55
As you said, this is related to Python 2.7. Since version 6,  more-itertools module targets only Python 3.x:

> 6.0.0
> Major changes:
> Python 2.7 is no longer supported. The 5.0.0 release will be the last version targeting Python 2.7.
> All future releases will target the active versions of Python 3. As of 2019, those are Python 3.4 and above.
> 

Therefore, you can try specifying a version for more-itertools lower or equal to 5.0.0 in the requirements.txt file, or just upgrade your code to Python 3 :)

**Comment by javijjavi** [comment] 2020-05-18 19:43
Ohhh thank you very much, that was the problem i solved in a second!

**Comment by dineshshetty** [comment] 2020-12-11 04:26
Closed as problem solved.

**Closed by dineshshetty** 2020-12-11 04:26 UTC
